chore(rsc): add `@cloudflare/vite-plugin` example (#926)
- Part of https://github.com/hi-ogawa/vite-plugins/issues/924

I think it mostly works as is. We can just simply ignore `importSsr/importRsc` and use service binding instead.

## todo

- [x] update all cloudflare related packages https://github.com/hi-ogawa/vite-plugins/pull/928
- [x] dev
- [x] build / preview
  - [x] server cannot import out-of-root artifact as external? `import "../client/__vite_rsc_assets_manifest.js"`. we should probably fixed this by ensuring these manifest live in `dist/ssr` and `dist/rsc` instead of `dist/client`
    - https://github.com/hi-ogawa/vite-plugins/pull/929
- [x] test
- [x] deploy https://vite-rsc-react-router.hiro18181.workers.dev
- [ ] is it possible without a separate worker?
  - it can for build. not sure dev.
- [ ] `findSourceMapURL` features not working due to missing `eval`?
- [x] `resolve.external` should be actually `optimizeDeps.include` https://github.com/hi-ogawa/vite-plugins/pull/927
- [ ] check with cloudflare team about allowing `optimizeDeps.exclude` (for framework packages). For now, cloudflare plugin is patched to silence this error.

```
Error: The following environment configurations are incompatible with the Cloudflare Vite plugin:
        - "ssr" environment: `optimizeDeps.exclude`: ["@hiogawa/vite-rsc"]
        - "ssr" environment: `resolve.external`: ["@hiogawa/vite-rsc/vendor/react-server-dom/client.edge"]
        - "rsc" environment: `optimizeDeps.exclude`: ["@hiogawa/vite-rsc"]
To resolve this issue, avoid setting `optimizeDeps.exclude` and `resolve.external` in your Cloudflare Worker environments.
```