fix: avoid ssr build on browser build failure (#429)
`closeBundle` is called regardless of build error, so moving it `writeBundle` (like Sveltekit and Remix do) helps stopping a build properly when first build is broken.

Currently, ssr build continues (and is destined to fail) even if browser build fails and the error message in that case is very cryptic like:

```
▶▶▶ REACT SERVER BUILD (browser) [3/4]
✓ 38 modules transformed.
▶▶▶ REACT SERVER BUILD (ssr) [4/4]
vite v5.2.3 building SSR bundle for production...
✓ 2 modules transformed.
x Build failed in 9ms
x Build failed in 881ms
error during build:
Error: [vitePluginReactServer:build] [virtual-virtual:route-manifest] Could not load virtual:route-manifest (imported by ../../dist/entry/server.js): TinyAssertionError
```